name: CI

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: build-linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        timeout-minutes: 15
        run: ci/build.sh

      - name: build-macOS
        if: ${{ matrix.os == 'macos-latest' }}
        timeout-minutes: 15
        run: ci/macOS.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/
          retention-days: 21
