name: CI

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: build-linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ci/build.sh

      - name: build-macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: ci/build.sh
